name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
